name: Build Spring Boot and ReactJS Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Amazon Corretto 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      #      - name: Install npm dependencies
      #        run: npm install
      #        working-directory: ./UI/hello-api-ui
      #
      #      - name: Build React app
      #        run: npm run build
      #        working-directory: ./UI/hello-api-ui

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Spring Boot project
        run: ./gradlew build