name: Build Spring Boot and ReactJS Project

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Amazon Corretto 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Get the closest tag
        id: tag
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo TAG_NAME=$TAG_NAME >> $GITHUB_ENV

      - name: Build Spring Boot project
        run: ./gradlew clean build -Pversion=${{ steps.tag.outputs.TAG_NAME }}
        env:
          TAG_NAME: ${{ steps.tag.outputs.TAG_NAME }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        id: tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/heads/release/}"
          git tag "v$TAG_NAME"
          git push origin "v$TAG_NAME"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Spring Boot project with tag
        run: |
          ./gradlew build publish -Pversion=${{ steps.tag.outputs.TAG_NAME }} \
          -Daws.accessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -Daws.secretAccessKey=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -Daws.region=${{ secrets.AWS_DEFAULT_REGION }} \
          -Daws.bucketName=${{ secrets.AWS_BUCKET }}
        env:
          TAG_NAME: ${{ steps.tag.outputs.TAG_NAME }}
